-- V10: Thống kê truy cập riêng cho Admin.
-- Có thể chạy lại an toàn trong Supabase SQL Editor.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (event_type in ('page_view','apply_click','zalo_click','call_click')),
  path text not null,
  job_slug text,
  referrer text,
  session_id text,
  device_type text
);

create index if not exists analytics_events_created_at_idx
on public.analytics_events (created_at desc);

create index if not exists analytics_events_event_type_idx
on public.analytics_events (event_type);

create index if not exists analytics_events_job_slug_idx
on public.analytics_events (job_slug);

alter table public.analytics_events enable row level security;

drop policy if exists "public can submit analytics events" on public.analytics_events;
drop policy if exists "authenticated can read analytics events" on public.analytics_events;

create policy "public can submit analytics events"
on public.analytics_events for insert
to anon, authenticated
with check (true);

create policy "authenticated can read analytics events"
on public.analytics_events for select
to authenticated
using (true);
