-- Chạy 1 lần để đưa 6 tin hiện tại vào bảng jobs.
insert into public.jobs (company_name,slug,location,job_title,salary,shift,age_requirement,gender_requirement,description,requirements,benefits,hr_name,hr_phone,hr_zalo,image_url,is_active,is_urgent)
values
('IDC Fluid','idc-fluid','KCN Đất Đỏ','Sản xuất kim loại, vòi nước inox rửa tay',E'Thu nhập khoảng 10–15 triệu/tháng\nLắp ráp/gia công: ca ngày 250.000đ, ca đêm 310.000đ\nRen/dập: ca ngày 280.000đ, ca đêm 340.000đ','Xoay ca được','22+','Nam / Nữ','Sản xuất kim loại và vòi nước inox rửa tay. Công việc gồm lắp ráp, gia công, kiểm hàng, đứng máy, kho và các công đoạn ren/dập.',E'Sức khỏe phù hợp công việc nhà máy\nCó thể xoay ca',E'Được đào tạo nếu chưa có kinh nghiệm\nBHXH, BHYT theo chính sách\nHỗ trợ ứng lương hàng tuần theo chính sách','Hậu','0868660068','0868660068','/media/idc-fluid.jpg',true,true),
('DNP','dnp','KCN Đất Đỏ','Công nhân sản xuất nhựa, bao bì nhựa',E'Ca ngày 12h: 408.000đ\nCa đêm 12h: 497.000đ\nChủ nhật ca ngày 12h: 690.000đ\nTăng ca ngày thường: 42.000đ/giờ\nTăng ca Chủ nhật: 57.500đ/giờ\nChuyên cần: 300.000đ/25 công','Ca 12 tiếng','18+','Nam / Nữ','Sản xuất nhựa, bao bì nhựa và các công đoạn hỗ trợ trong nhà máy. Phù hợp người muốn đi làm sớm và có nhu cầu tăng ca.','CCCD bản gốc',E'BHXH, BHYT, BHTN\nThưởng lễ, Tết, tháng 13 theo chính sách\nCông việc ổn định, có tăng ca','Hậu','0868660068','0868660068','/media/dnp.jpg',true,false),
('Dongjin','dongjin','KCN Đất Đỏ','Lắp ráp mô tơ, dây điện & linh kiện ô tô',E'8h ngày: 251.500đ\n12h ngày: 377.700đ\n8h đêm: 301.500đ\nTăng ca khoảng 35.000–61.000đ/giờ','7h–15h + tăng ca','16+','Nam / Nữ','Sản xuất mô tơ tản nhiệt ô tô, động cơ làm mát, motor DC công nghiệp; dây điện ô tô (wire harness), máy đề, máy phát điện và phụ kiện động cơ.','Có thể làm việc trong môi trường sản xuất công nghiệp',E'Chuyên cần 300.000đ/26 công\nNăng suất + đứng máy: 200.000–1.000.000đ\nBHXH, BHYT, BHTN','Kim Anh','0334677276','0334677276','/media/dongjin.jpg',true,false),
('DJ&M Solution','djm-solution','Suối Rao, Châu Đức','Dây điện ô tô, mô tơ & linh kiện điện',E'8h ngày: 251.500đ\n12h ngày: 377.700đ\n8h đêm: 301.500đ\nTăng ca khoảng 35.000–61.000đ/giờ','7h–15h, tăng ca đến 18h hoặc 21h','17–45','Nam / Nữ','Sản xuất dây điện ô tô (wire harness), mô tơ tản nhiệt, động cơ làm mát, motor DC công nghiệp, máy đề, máy phát điện và các phụ kiện liên quan.',E'CCCD bản gốc\nPhỏng vấn đạt có thể đi làm ngay',E'Có tăng ca\nThu nhập tăng theo số giờ làm','Ms Hoa','0886935805','0886935805','/media/djm-solution.jpg',true,false),
('An An','an-an','KCN Đất Đỏ','Sản xuất da nhân tạo',E'Ca ngày: 430.000đ\nCa đêm: 490.000đ\nChuyên cần: 260.000đ','Xoay ca 12 tiếng','18–45','Nam / Nữ','Sản xuất da nhân tạo trong nhà máy, làm việc với các cuộn vật liệu và công đoạn sản xuất theo dây chuyền. Có ca ngày và ca đêm.','CCCD bản gốc hoặc VNeID',E'BHXH theo quy định\nCông việc ổn định','Ms Hoa','0886935805','0886935805','/media/an-an.jpg',true,false),
('Hải Âu','hai-au','KCN Đất Đỏ','Mài, xi mạ, đúc kim loại, phun sơn & kho',E'Thử việc: 6.730.000đ\nChính thức: 7.700.000đ\nThợ tay nghề ≥1 năm: 8.400.000đ\nCó thêm các khoản phụ cấp khác','Hành chính + tăng ca, xoay ca được','18+','Nam / Nữ','Gia công nội thất vòi inox và các bộ phận mài kẽm/mài đồng, xi mạ kẽm/xi mạ đồng, đúc kim loại, phun sơn, gia công và kho.',E'CCCD + hồ sơ\nKhông cần kinh nghiệm, được đào tạo',E'Hỗ trợ cơm ca\nBHXH, BHYT\nThưởng lễ, Tết\nLương hàng tháng đúng hạn','Trang','0939296153','0939296153','/media/hai-au.jpg',true,true)
on conflict (slug) do update set
  company_name=excluded.company_name,location=excluded.location,job_title=excluded.job_title,salary=excluded.salary,shift=excluded.shift,age_requirement=excluded.age_requirement,gender_requirement=excluded.gender_requirement,description=excluded.description,requirements=excluded.requirements,benefits=excluded.benefits,hr_name=excluded.hr_name,hr_phone=excluded.hr_phone,hr_zalo=excluded.hr_zalo,image_url=excluded.image_url,is_active=excluded.is_active,is_urgent=excluded.is_urgent,updated_at=now();
